### ISSUE TITLE
joomshopping.pro

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#19]
### Название сайта  
joomshopping.pro  

### Ссылка на сайт 
https://joomshopping.pro/

### Описание 
Незаконная продажа дополнений и расширений для популярного компонента магазина JoomShopping. Продает устаревшие расширения, которые неполноценно или вообще не работают на последних версиях Joomla и JoomShopping. Обещанная поддержка по факту не оказывается. Подозрения в мошенничестве.

**Comment by b2z** [comment]
За. Пусть придёт и докажет, что это не так.

**Comment by pavluk** [comment]
Я давно покупал фильтр, были проблемы, поддержка помогала.
Адекватные ребята.

**Comment by b2z** [comment]
Если что, у нас презумпция виновности :) Обратное надо бы доказать. Это так, к слову ;)
