### ISSUE TITLE
Аватар организации

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#2]
Необходимо сделать Аватар для страницы организации.
https://github.com/JoomlaRu 
Без него организация выглядит "брошено"

Возможно понадобиться одобрение OSM на использования TM

**Comment by b2z** [comment]
Я предлагаю не заморачиваться и использовать просто лого Joomla. Не уверен, что нужно что-то большее.

Насчёт разрешения, по моему не требуется. Попробую уточнить.

**Comment by Septdir** [comment]
> Я предлагаю не заморачиваться и использовать просто лого Joomla. Не уверен, что нужно что-то большее.

Можно флаг России в правый угол лого добавить и все.

Сделать я сейчас у компа и открыть PS не проблема.

**Comment by Septdir** [comment]
![1](https://user-images.githubusercontent.com/18382023/47617892-74fa7a00-dadd-11e8-84d9-b45c7ac1a304.png)
Я конечно не мастер фотошопа =)

**Comment by b2z** [comment]
Нет, флаг лишнее. Мы же не из России... Мы просто все русскоязычные ;)

**Comment by Septdir** [comment]
Но русский язык же на сайтах флагом отмечают.  
Хотя согласен выглядит как будто русская локализация.

Аватару взял эту.
https://avatars2.githubusercontent.com/u/751633?s=200&v=4
Можно ее и поставить

**Comment by proweb** [comment]
ну может аббревиатуры RU или RUS будет достаточно где то на лого.

**Comment by b2z** [comment]
Я вышел на Trademark team lead - Claire. Задал ей вопрос, как получить разрешение на использование лого.

**Comment by b2z** [comment]
Пока с ней общаемся, она обратила внимание на то, что на Joomlaportal неправильный disclaimer, не хватает английского текста. Вот правила https://tm.joomla.org/disclaimers.html.

Вообщем нужно проверить на соответствие все три наших основных сайта:
https://joomlaportal.ru  https://joomlaforum.ru https://joomla-support.ru

**Comment by Septdir** [comment]
А с аватаром то что?

Кстати нам наверное тоже надо disclaimer добавить.

**Comment by b2z** [comment]
Пока ничего... Она задала вопрос, какая вообще наша цель создания организации на Github, я ей ответил и спать пошёл :) 
> Кстати нам наверное тоже надо disclaimer добавить.

Да, это обязательно.

**Comment by b2z** [comment]
Нас развернули :) Эту организацию пришлось переименовать. Посему аватар может быть абстрактным :) И disclaimer тоже походу не нужен. Ну по крайней мере пока.

**Comment by Septdir** [comment]
@b2z disclaimer можно.

**Comment by Septdir** [comment]
![l1](https://user-images.githubusercontent.com/18382023/48100501-945b7a80-e234-11e8-9b2a-f61e3bb630df.png)
Я чудо мастер фотошопа

**Comment by b2z** [comment]
@Septdir вырви глаз! :) Может просто картинку природы, а? Тупо что-то абстраткное.
https://unsplash.com/t/nature

**Comment by Septdir** [comment]
@b2z Не вырви глаз, а обложка какого старого учебника.
Абстрактное можно, но чтобы ассоциировалось, так что не природу. Ну или просто текст.

**Comment by b2z** [comment]
https://jdenticon.com/#icon-RUJL

**Comment by Septdir** [comment]
@b2z Норм.

**Comment by b2z** [comment]
Поставил :+1:
