### ISSUE TITLE
Заявка jturbo.ru 😁

### ISSUE THREAD

**Issue by CB9TOIIIA** [RUJL/rujl.github.io#21]
Название сайта:  Яндекс Турбо для Joomla и Яндекс Дзен
Ссылка на сайт:  https://jturbo.ru/
Описание:  Расширение для Joomla Яндекс Турбо  и Яндекс Дзен

**Comment by Septdir** [comment]
А самому PR лень сделать?

Ну ок мне не лень.

**Comment by CB9TOIIIA** [comment]
> А самому PR лень сделать?
> 
> Ну ок мне не лень.

![image](https://user-images.githubusercontent.com/1074710/49013005-62329e00-f18c-11e8-8275-3f7a2918bd32.png)

я нажимал и этот шаблон выше вышел. Что-то не так?

**Comment by b2z** [comment]
А @CB9TOIIIA не может делать PR, я его пока убрал как Collaborator.
И давайте такие вещи без PR, сами себя не добавляем. Теперь только через Issue.

**Comment by Septdir** [comment]
Это мерджить не может. А PR с форка может =)

P.S плин забыл close в коммите написать.

**Comment by Septdir** [comment]
close by pr #27
