### ISSUE TITLE
Визитка программиста seosm.ru 👀

### ISSUE THREAD

**Issue by CB9TOIIIA** [RUJL/rujl.github.io#22]
Название сайта:  Разработка расширений Joomla! и JBZoo
Ссылка на сайт:  https://seosm.ru/
Описание: сайт Евгения К.  - веб-программист, спикер международной конференции JoomlaDay, специалист по CMS Joomla!

**Comment by b2z** [comment]
За добавление в список. Проверенный веб-мастер :+1:

**Comment by Septdir** [comment]
+1
