### ISSUE TITLE
[RFC] Отдельный список для веб-мастеров

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#26]
Предложение отделить в 2 списка на одной или двух страницах, список веб мастеров.

То бишь сайты где можно скачать купить расширения отдельно. А рекламные страницы веб мастеров отдельно.

**Comment by CB9TOIIIA** [comment]
👍 https://seosm.ru/

**Comment by b2z** [comment]
Плюсую. Я всё думал, как отделить так правильно. Я за то, чтобы сделать отдельный список webmasters.md :)

Вопрос - кто будет подтверждать добавление?

**Comment by AlekVolsk** [comment]
как бы связь с вебмастером надо держать и понимать, что он реально вебмастер, а не левый манагер, служащий прокладкой между клиентом и школяром

**Comment by b2z** [comment]
Ну я бы предложил так, что хотя бы пару проверенных человек из сообщества оставили свои отзывы.

**Comment by Septdir** [comment]
@b2z согласен. пару отзывов норм.

У меня второй вопрос. А нужен ли черный список.. ибо он в разы сложнее по модераторию.

**Comment by b2z** [comment]
@Septdir пока нет, на форуме же есть отзывы.

**Comment by kernusr** [comment]
Кстати, по какому принципу будут отбираться вебмастера?
Попасть сможет любой, даже тот кто, максимум, в хеликсе галочек натыкать может? Или, всёже, нужно предоставить какие-то более весомые доказательства своей пренадлежносте к касте Joomla-мастеров?

**Comment by Septdir** [comment]
А если так. По отзыву от 2-х человек которые уже в списке.

**Comment by kernusr** [comment]
И, хотябы, 1 PR для Joomla CMS =)

**Comment by Septdir** [comment]
@kernusr PR PR'у рознь.

**Comment by b2z** [comment]
Мне всё таки кажется, что достаточно, чтобы несколько проверенных человек из сообщества оставили свои отзывы.

Кстати, а как будет оформлять? Название со ссылкой плюс описание?

**Comment by Septdir** [comment]
@b2z примерно так, но надо определиться с форматом описания. 
Нужно что-то вроде  
`Краткий список услуг`

**Comment by b2z** [comment]
@Septdir а я не уверен, что такое нужно. Иначе список будет очень длинно неудобный.

**Comment by Septdir** [comment]
@b2z может ты и прав.  
Тогда можно вообще без описания.  А то будет одно и то же только разными словами. К тому же вся инфа и так есть на сайтах.

Это же не список студий где надо знать где шаблоны есть, а где только компоненты.

**Comment by b2z** [comment]
Тогда как-то так:
[Разработка расширений Joomla! и JBZoo](https://seosm.ru)
[Example 2](https://github.com)
[Example 3](https://github.com)

**Comment by Septdir** [comment]
Закрыто #43
