### ISSUE TITLE
Добавить описание

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#3]
Добавить описание в [readme](https://github.com/JoomlaRu/docs/blob/master/README.md)

В описание указать цели создания.

---
## Заголовок
Наша цель - сделать Joomla! CMS лучше / Our aim is to make Joomla! CMS even better

## Кто мы?
Мы - русскоязычное сообщество любителей Joomla! CMS.

## Зачем мы тут?
Наша цель - сделать Joomla! CMS лучше.

## А можно конкретнее?
Если вы нашли ошибку в CMS и знаете как её решить или хотите предложить улучшение, но не знаете как правильно создать Issue / оформить Pull Request, мы вам поможем.

Вам необязательно знать английский, так как мы общаемся с вами на русском и далее продвигаем ваши идеи и предложения в репозиторий Joomla! CMS.

Мы также пытаемся собрать всё самое полезное для разработчиков в одном месте.

## Мне это интересно, с чего начать?
Ссылки ниже помогут вам выбрать интересующее вас направление.
Вы также можете начать с нашей страницы помощи. Там вы найдёте необходимую информацию о том, как вы можете помочь в развитии Joomla! CMS.

**Comment by Septdir** [comment]
Я тут примерно накидал одно.
Цель помочь русскоговорящим и ленивым разработчикам делать PR, а пользователям issue, тем самым увеличивая вклад русскоговорящего сообщества в развитие ядра Joomla. А так же собрать все полезное, для разработки на базе CMS Joomla.

**Comment by b2z** [comment]
Может в таком стиле:

## Кто мы?
Мы - русскоязычное сообщество любителей Joomla! CMS.

## Зачем мы тут?
Наша цель - сделать Joomla! CMS лучше.

## А можно конкретнее?
Если вы нашли ошибку в CMS и знаете как её решить или хотите предложить улучшение, но не знаете как правильно создать Issue / оформить Pull Request, мы вам поможем.

Вам необязательно знать английский, так как мы общаемся с вами на русском и далее продвигаем ваши идеи и предложения в репозиторий Joomla! CMS.

Мы также пытаемся собрать всё самое полезное для разработчиков в одном месте.

## Мне это интересно, с чего начать?
Ссылки ниже помогут вам выбрать интересующее вас направление. Вы также можете начать с нашей страницы в Wiki. Там вы найдёте необходимую информацию о том, как вы можете помочь в развитии Joomla! CMS.

**Comment by Septdir** [comment]
@b2z хорошо, во всяком случае для начала отлично.
Вот только не уверен.
Русскоязычное или русскоговорящие как правильнее.

Только в PR #1 будет конфликт. Я там оглавление(кажись кривое кстати) в readme сделал.

**Comment by b2z** [comment]
Фигово только то, что это описание будет в репе docs, но в организацию вроде тоже можно добавить?

**Comment by Septdir** [comment]
Да можно, но та input type="text" так что много не напишешь.

**Comment by b2z** [comment]
Немного переделал раздел с чего начать. Предлагаю такой текст:
## Мне это интересно, с чего начать?
Ссылки ниже помогут вам выбрать интересующее вас направление.
Вы также можете начать с нашей страницы помощи. Там вы найдёте необходимую информацию о том, как вы можете помочь в развитии Joomla! CMS.

**Comment by Septdir** [comment]
@b2z Может сделаешь сразу PR и там продолжим обсуждения?

**Comment by b2z** [comment]
@Septdir а смысл? Потом каждый раз пушить изменения? Лучше здесь уже всё обсудить и сделать один раз ;)

**Comment by Septdir** [comment]
@b2z Ну так можно view нажать.

Хотя я сейчас первый пост тут поправлю и будет своего рода демо.
