### ISSUE TITLE
Заявка в белый список Fictionlabs.ru

### ISSUE THREAD

**Issue by fiction13** [RUJL/rujl.github.io#32]
### Название сайта
Fictionlabs.ru

### Ссылка на сайт
[https://fictionlabs.ru/](https://fictionlabs.ru/)

### Описание
Разработка расширений для Joomla, в том числе Google AMP и Yandex Turbo. Распространение созданных мной решений.

**Comment by b2z** [comment]
Привет!

А есть кто-то из сообщества Joomla, кто может подтвердить твою кандидатуру?

**Comment by fiction13** [comment]
Добрый день.

Женя (aka Святоша) может подтвердить ;-)

**Comment by fiction13** [comment]
https://tech.yandex.ru/turbo/, еще Яндекс может подтвердить, что я хороший :-)

**Comment by b2z** [comment]
@CB9TOIIIA что скажешь?
Ну Яндекс подтверждает только твои расширения - это частное.
Важно, чтобы мы понимали, что ты действительно хороший и проверенный исполнитель.

**Comment by CB9TOIIIA** [comment]
И Яндекс меня тоже рекомендует 😁 Хороший :) и кодер хороший и Дима зовут) тёзку добавляй. Это кореш из #jbzoo сообщества :))
