### ISSUE TITLE
[Страница] Информация для разработчика

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#34]
Заполнить страницу 
[Информация для разработчика](https://jdevru.github.io/developer/)

**Comment by b2z** [comment]
Вот если бы ты попал на такую страницу, чтобы ты хотел на ней увидеть?

Я бы наверное:
**API** - ссылка на официальный API + возможно ещё какие-то ссылки
**Документация** - внятная структура с деревом разделов, внутри которых ссылки на полезные ресурсы. Своего рода индекс документации разработчика. То есть всё что есть и раскидано сейчас по просторам интернета, но в одном месте.
**Базовые понятия** - это своего рода документация-глоссарий. Пояснения основных парадигм CMS (возможно со ссылками на разделы документации): application - приложение, component- компонент, plugin - плагин, module - модуль, template - шаблон, form - форма, routing - роутинг, MVC и т.д.

**Comment by progreccor** [comment]
И главное - актуальное! А не по джумла 1.5

**Comment by b2z** [comment]
Можно как у [WP](https://codex.wordpress.org/Developer_Documentation) и [Drupal](https://www.drupal.org/docs/develop) - по направлениям.

**Comment by b2z** [comment]
Вот ещё классное оформление, мне понравилось - [Yii Docs](https://www.yiiframework.com/doc/guide/2.0/ru).

**Comment by b2z** [comment]
И ещё как вариант - у Дениса Сметанникова [неплохо](http://joomla-book.ru/development).

**Comment by b2z** [comment]
Пособирал в инете, откуда можно брать контент / концепт:
https://cmscafe.ru/docs/joomla/developer
http://inet-reklama.com/blog.html
http://joomla-book.ru/development
http://jdevelop.info/articles/develop-joomla
https://boxapp.net/blog/joomla
https://docs.joomla.org/Portal:Developers
https://docs.joomla.org/Glossary

**Comment by b2z** [comment]
Как же я про CMScafe забыл ;) У нас тоже неплохо смотрится страничка https://cmscafe.ru/docs/joomla

**Comment by proweb** [comment]
API - нужно, но без примеров использования (Классов,методов и т.д.) оно имеет смысл только для разработчиков уровня @Septdir @b2z и т.п. Как пример Codex WP изначально содержит - название функции, а ниже куски кода с примером использования - считаю что это наиболее логичный вариант.

Документация - для меня это скорее статьи по типу Посмотри и Повтори, то как это писал @b2z - тому отличный пример, что наглядно видно даже по комментариям к его документации. 

Единственная проблема, которую я вижу - поддержка документации в актуальном состоянии, API и сама Joomla намного более изменчивая система чем тот же WP, прошел месяц, а тот метод или сниппет который ты достаточно удобно использовал в течение года-двух, вдруг перестает работать - как пример, хороший старт сделанный David Hurley, с его серией статей Joomla Development 101, а также с [учебным компонентом Lendr](https://github.com/sparkbuilt/lendr/) на который чувак забил полностью, уйдя от Joomla в коммерческую разработку - теперь те кто пытаются повторить и сделать свой компонент - обламываются получая Error а [issue](https://github.com/sparkbuilt/lendr/issues) никто не собирается решать...

Статьи http://inet-reklama.com/blog.html - тоже были в свое время интересны и полезны, но дядька тоже видимо устал писать

Помимо доков нужен список ресурсов (URL) где новичок-разработчик может поискать ответы, это безусловно stackoverflow - там много полезного, но подчас хер найдешь, спасают тока закладки. Joomlaforum - по сути превратился в "курилку", новичка там особо не ждут. JoomlaPortal - слабо наполняется и теперь вообще не понимаю для чего он нужен если кроме PR расширений форумчан там по сути не осталось ничего.

**Comment by proweb** [comment]
По поводу внешнего вида особо нового ничего не придумали, все старо как мир
Заголовок - Документация по {тут название}
Строка поиска по контенту - обычный input (если сильно охота можно заморочится с live ajax search)
Основные категории/разделы документации, возможно то что было добавлено последним или имеет больше всего просмотров
Но опять же вопрос - что это будет за сайт - переписывать весь API - я думаю никто не потянет.
Хотя примеры есть и примеры удачные достаточно, так например WP-Kama - лично я лучше ресурса по докам для соседствующей с нами CMS не видел.

Ну и плюс, возможно стоит сделать какой то функционал по обратной связи - типа рубрику Вопросы, отвечать и писать ответы на нее не считаю обязательным, но как средство аналитики и то что интересует посетителя конкретного в данный момент по докам, может быть полезно.

**Comment by b2z** [comment]
> Единственная проблема, которую я вижу - поддержка документации в актуальном состоянии, API и сама Joomla намного более изменчивая система чем тот же WP, прошел месяц, а тот метод или сниппет который ты достаточно удобно использовал в течение года-двух, вдруг перестает работать

Вот это действительно боль...
> По поводу внешнего вида особо нового ничего не придумали, все старо как мир
Строка поиска по контенту - обычный input (если сильно охота можно заморочится с live ajax search)
Основные категории/разделы документации, возможно то что было добавлено последним или имеет больше всего просмотров

Ну вот мне кажется, что по [Yii](https://www.yiiframework.com/doc/guide/2.0/ru) отлично в этом плане сделано, не? И на [CMSCafe](https://cmscafe.ru/docs/joomla) мы что-то подобное тоже сделали.

WP-kama конечно круто и на это надо равняться, но блин - такое тяжело потянуть.

**Comment by proweb** [comment]
Ну в целом то что сделано для Yii достаточно норма смотрится, да.
Если взять такую структуру в целом то думаю пошло бы.

**Comment by b2z** [comment]
Начал накидывать:
https://docs.google.com/document/d/1ix9lJ5Couo-sCYTt0PA3FyHRNYc0-4v9X9vdHXVs2yI

**Comment by b2z** [comment]
https://jpath.ru в процессе разработки. Stay tuned :)
https://t.me/jpathru
https://vk.com/jpathru
