### ISSUE TITLE
[Страница] Идеи и предложения

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#36]
Заполнить страницу 
[Идеи и предложения](https://jdevru.github.io/ideas/)

**Comment by b2z** [comment]
Тут пока даже не знаю - может просто информация о том, как предлагать свои идеи и предложения? Ну типа создайте Issue или научитесь делать PR... А может нам вообще не нужна такая страничка?

**Comment by b2z** [comment]
Это отметаем?
