### ISSUE TITLE
Добавить topics к репозиторию

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#4]
Ака теги которые под описанием.

**Comment by b2z** [comment]
Ты про репу joomla-cms?

**Comment by Septdir** [comment]
Ну docs тоже парочка не помешает. joomla russian к примеру.

**Comment by b2z** [comment]
Topics (separate with spaces)
Add topics to categorize your repository and make it more discoverable.

Лейблов не хватает?

**Comment by Septdir** [comment]
Да. Не то чтобы это было архи важно но все же.

**Comment by b2z** [comment]
Мхм, для joomla-cms наверное и нет смысла добавлять, это же форк. В оригинале всё уже добавлено. Для docs - даже и не знаю, что там нужно. По логике это наша внутренняя вешь, делать репу более discoverable нет особого смысла?

**Comment by b2z** [comment]
Добавил в rujl.github.io: joomla, cms и docs :smile_cat:

**Comment by Septdir** [comment]
Ну и норм. 
Закрываем.
