### ISSUE TITLE
Septdir Workshop

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#45]
### Название сайта
Septdir Workshop

### Ссылка на сайт
https://www.septdir.com/

### Описание
Расширения  для Joomla CMS

**Comment by b2z** [comment]
Думаю, что тут двух голосов не нужно :)

**Comment by Septdir** [comment]
@b2z каких двух слов Joomla и CMS может быть. 
И вообще просто добавь. А то добавлять самого себя мне совесть не позволяет.
