### ISSUE TITLE
Добавление сайта https://icekompot.blogspot.com/ в черный список

### ISSUE THREAD

**Issue by kernusr** [RUJL/rujl.github.io#47]
### Ссылка на сайт
[https://icekompot.blogspot.com/](https://icekompot.blogspot.com/)

### Описание
За пропаганду вареза, вот в этой статье [https://icekompot.blogspot.com/2016/12/joomla-3-virtuenart-3-csvi-export.html](https://icekompot.blogspot.com/2016/12/joomla-3-virtuenart-3-csvi-export.html)

**Comment by b2z** [comment]
Я за

@Septdir @progreccor @zikkuratvk

**Comment by progreccor** [comment]
Статья 2016 года. Не много ли чести для заштатного блога ?

**Comment by kernusr** [comment]
@progreccor она хоть и старая, но в ней прям по тексту написано "актуализировано в марте 2018".

**Comment by progreccor** [comment]
Ну тогда вот эта статья
https://icekompot.blogspot.com/2018/09/csvi-73.html?m=1

В принципе согласен

Пропаганда и распространение варез

**Comment by b2z** [comment]
Добавил
