### ISSUE TITLE
добавить в ЧС

### ISSUE THREAD

**Issue by nevigen** [RUJL/rujl.github.io#49]
### Ссылка на сайт
joom-shop.com

### Описание
варез

**Comment by b2z** [comment]
Хмм, а в чём варез?

**Comment by nevigen** [comment]
например
https://joom-shop.com/katalog/addons-for-joomshopping/one-page-registration-for-joomshopping.html
https://nevigen.com/ru/addons/onestepcheckout-joomshopping.html

все перечислять не обязательно ?

**Comment by b2z** [comment]
Реселлеры? :( Добавил
