### ISSUE TITLE
[RFC] Whitelist / BlackList

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#5]
Стоит ли делает человеческий Белый и черный список разработчиков расширений.
В белом листе сайты крупных студий.
В черном варезники и складчины

**Comment by b2z** [comment]
Я за

**Comment by proweb** [comment]
+1

**Comment by b2z** [comment]
А как будем принимать заявки на Белый список?

**Comment by Septdir** [comment]
@b2z Шалблон issue и PR

Или ты про проверку caйтов?

**Comment by b2z** [comment]
Не, я именно про заявки. Да, через Issue в самый раз. Опишем это в правилах.
