### ISSUE TITLE
Добавление в белый список wedal.ru

### ISSUE THREAD

**Issue by wedal** [RUJL/rujl.github.io#50]
## Добавление в белый список
wedal.ru

### Название сайта
Создание сайтов на Joomla

### Ссылка на сайт
https://wedal.ru

### Описание
Уроки Joomla, бесплатные авторские расширения Joomla, создание сайтов и расширений на заказ.

**Comment by b2z** [comment]
Добавил

**Comment by wedal** [comment]
Спасибо!
