### ISSUE TITLE
Белый список

### ISSUE THREAD

**Issue by arenamax** [RUJL/rujl.github.io#54]
## Добавление в белый список
Привет! Хочу в белый список.

### Название сайта
ArenaM

### Ссылка на сайт
https://arenam.ru

### Описание
Разработка расширений для Joomla. Список наших бесплатных и коммерческих расширений, поддержка и документация.

**Comment by b2z** [comment]
Добавлено.

**Comment by arenamax** [comment]
Большое спасибо!!!
