### ISSUE TITLE
Актуализировать белый список

### ISSUE THREAD

**Issue by Sulpher** [RUJL/rujl.github.io#58]
Добавить Sovmart и Radicalmart
убрать https://joomext.ru. домен бросили, кто-то купил и теперь тематика - ставки.

**Comment by b2z** [comment]
Сделано

**Comment by Sulpher** [comment]
Sovmart и RadicalMart не вижу :-)

**Comment by b2z** [comment]
https://github.com/JPathRu/jpath.ru/blob/master/whitelist/index.md они тут есть - в конце.

**Comment by Sulpher** [comment]
я вообще здесь смотрел: https://jpath.ru/whitelist :-)
тк с форума ссылка ведет на эту статью. в гитхабе даже не знал, что есть список этот. 
актуализируйте на сайте.

**Comment by Sulpher** [comment]
Я совсем забыл про Profibits. давай тоже добавим :-)

**Comment by b2z** [comment]
> Я совсем забыл про Profibits. давай тоже добавим :-)

Докинул
