### ISSUE TITLE
[RFC] Разъяснения по поводу лицензий

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#6]
Думаю будет полезным разметить информацию информацию о то что такое лицензии GPL и MIT
И другие лицензии использующиеся в расширениях

**Comment by b2z** [comment]
Разве в интернете не достаточно материалов на эту тему?

**Comment by Septdir** [comment]
Да достаточно, но все они разрозненные, хотя можно просто в полезные ссылки добавить если найти нормальную.

**Comment by progreccor** [comment]
Мне кажется что совершенно лишнее. В реальной жизни никому не надо.

**Comment by progreccor** [comment]
опечатка в слове "Разяснения"

**Comment by Septdir** [comment]
> опечатка в слове "Разяснения"

Исправил.

**Comment by Septdir** [comment]
Закрыто. Если понадобиться, добавим в полезные ссылки.
