### ISSUE TITLE
[RFC] Изменить заголовок и добавить веб сайт.

### ISSUE THREAD

**Issue by Septdir** [RUJL/rujl.github.io#8]
Изменить заголовок. Он же Description
Потому что "Документация" в заголовке [сайта] (https://joomlaru.github.io/) выглядит не совсем верно.

И добавить веб сайт для удобства.

![screenshot_2018-10-29 septdirtestorg septdirtestorg github io](https://user-images.githubusercontent.com/18382023/47649131-4cca5400-db8d-11e8-86f7-376e5db7d5ff.png)

**Comment by b2z** [comment]
Заголовок - да... Что-то пока не пидумывается, как лучше назвать. Сайт добавил.

**Comment by b2z** [comment]
Не стал мудрить и добавил заголовок **Наша цель - сделать Joomla! CMS лучше**

**Comment by Septdir** [comment]
Для начала пойдет.
